[[redirects]]
from = "/redirect/https%3A%2F%2Ffolda.netlify.com%2F"
to = "https://folda.netlify.com/"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2Fisearthstillwarming.com"
to = "https://isearthstillwarming.com"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2F2019.metaprojection.ca"
to = "https://2019.metaprojection.ca"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2F2019.qhacks.io"
to = "https://2019.qhacks.io"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2Fwww.qvft.ca%2F"
to = "https://www.qvft.ca/"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2Frust-mandelbrot.netlify.app%2F"
to = "https://rust-mandelbrot.netlify.app/"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2Fwww.npmjs.com%2Fpackage%2Funitransform"
to = "https://www.npmjs.com/package/unitransform"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2Fwtformat.com%2F"
to = "https://wtformat.com/"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2Fgithub.com%2Frosslh"
to = "https://github.com/rosslh"
status = 301
force = true

[[redirects]]
from = "/redirect/https%3A%2F%2Fwww.linkedin.com%2Fin%2Frosslh"
to = "https://www.linkedin.com/in/rosslh"
status = 301
force = true